language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit
    - LUA=luajit2.0
    - LUA=luajit2.1

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - luarocks install moonscript

before_script:
  - luacheck --version
  - busted --version

script:
  - luacheck --no-unused-args --std max+busted *.lua spec
  - busted --verbose --coverage --output TAP

after_success:
  - luacov-coveralls --exclude spec --exclude $TRAVIS_BUILD_DIR/install
